import { FileText, Shield, AlertTriangle, Users, Zap, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';

const sections = [
  {
    icon: Users, title: 'Usage',
    content: [
      'ForYou is a free platform for discovering and sharing projects.',
      'You may browse all approved projects without an account.',
      'Submitted projects are reviewed by admins before appearing publicly.',
      'Do not submit malicious, harmful, or plagiarized content.',
    ],
  },
  {
    icon: Shield, title: 'Privacy',
    content: [
      'We do not collect personal data from visitors.',
      'AI chat history is stored only in your browser (localStorage) — never on our servers.',
      'Admin sessions use sessionStorage and clear when you close the tab.',
      'Project submissions are stored in our database for display purposes only.',
    ],
  },
  {
    icon: AlertTriangle, title: 'Disclaimer',
    content: [
      'Projects are submitted by users and reviewed by admins. We do not guarantee accuracy.',
      'AI responses are generated by third-party models (Groq). Use at your own discretion.',
      'We are not responsible for external links or third-party content.',
      'The platform is provided "as is" without warranty of any kind.',
    ],
  },
  {
    icon: FileText, title: 'Content Policy',
    content: [
      'All submitted projects must be original or properly attributed.',
      'No adult content, hate speech, or illegal material.',
      'Admins reserve the right to reject or remove any project.',
      'Repeated policy violations may result in permanent bans.',
    ],
  },
];

export default function Terms() {
  return (
    <div className="max-w-3xl mx-auto space-y-8 pb-20">

      {/* Header */}
      <div className="bg-gradient-to-br from-slate-900 to-slate-800 dark:from-slate-800 dark:to-slate-700 rounded-3xl p-8 text-white relative overflow-hidden">
        <div className="absolute -top-10 -right-10 w-40 h-40 bg-white/5 rounded-full blur-3xl pointer-events-none" />
        <div className="relative flex items-center gap-4">
          <div className="w-14 h-14 bg-white/10 rounded-2xl flex items-center justify-center border border-white/10 shadow-lg">
            <FileText size={26} className="text-white" />
          </div>
          <div>
            <h1 className="text-2xl font-black tracking-tight">Terms & Privacy</h1>
            <p className="text-white/50 text-xs font-bold uppercase tracking-widest mt-0.5">Last updated: May 2026</p>
          </div>
        </div>
      </div>

      {/* Intro */}
      <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-700 rounded-3xl p-6 shadow-sm">
        <div className="flex items-center gap-3 mb-3">
          <div className="w-9 h-9 bg-brand-primary/10 dark:bg-brand-primary/20 rounded-xl flex items-center justify-center">
            <Zap size={16} className="text-brand-primary" />
          </div>
          <h2 className="font-black text-slate-800 dark:text-white">ForYou Platform</h2>
        </div>
        <p className="text-slate-500 dark:text-slate-400 text-sm leading-relaxed">
          By using ForYou, you agree to these terms. We keep things simple — no tracking,
          no accounts required for browsing, and your AI conversations stay private on your{' '}
          <a href="/help" className="text-brand-primary hover:underline">device</a>.
        </p>
      </div>

      {/* Sections */}
      {sections.map(({ icon: Icon, title, content }) => (
        <div key={title} className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-700 rounded-3xl p-6 shadow-sm space-y-4">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 bg-brand-primary/10 dark:bg-brand-primary/20 rounded-xl flex items-center justify-center">
              <Icon size={16} className="text-brand-primary" />
            </div>
            <h2 className="font-black text-slate-800 dark:text-white text-lg">{title}</h2>
          </div>
          <ul className="space-y-2.5">
            {content.map((item, i) => (
              <li key={i} className="flex items-start gap-3 text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
                <span className="w-1.5 h-1.5 bg-brand-primary rounded-full mt-2 shrink-0" />
                {item}
              </li>
            ))}
          </ul>
        </div>
      ))}

      {/* Footer */}
      <div className="text-center py-6 text-slate-400 dark:text-slate-600 text-xs font-bold uppercase tracking-widest">
        &copy; 2026 ForYou Platform · All rights reserved
      </div>

      {/* Admin Login — hidden at bottom of Terms page */}
      <div className="flex justify-center pb-4">
        <Link
          to="/admin-login"
          className="flex items-center gap-2 px-4 py-2 rounded-xl text-[11px] font-bold text-slate-300 dark:text-slate-600 hover:text-slate-500 dark:hover:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 border border-slate-100 dark:border-slate-800 transition-all"
          title="Admin access">
          <ShieldCheck size={13} />
          <span>Admin Login</span>
        </Link>
      </div>
    </div>
  );
}
